### ISSUE TITLE
token revocation yields AttributeError

### ISSUE THREAD

**Issue by myq** [brunsgaard/yoloAPI#5]
Can you demonstrate how to revoke a token? Since you got rid of the client_secret (which I realize is not needed for grant type `password`), flask_oauth complains when I try to revoke it.

When I sent only the token as data, it said the client_id was missing, and when I sent both (see below), I received a traceback ending with 

> AttributeError: 'Client' object has no attribute 'client_secret'

To reproduce (use a valid client_id and access token):

> curl -k -d "client_id=zubq7vObWyX0PDLIzmIgmawSHBAJGu2gGzSo1IvX&token=1907uNB3PnFWyJGLOc2NKA5D0Xk2Qx" https://localhost:5000/oauth/revoke

**Comment by EmergentBehavior** [comment]
Haven't looked at this in a bit but I believe, because of the reasons you indicated, revocation is not currently supported with the example. @brunsgaard can chime in too if I'm mistaken.

**Comment by brunsgaard** [comment]
Hay Josh, I will take a look at this over the weekend.. just published my paper two days ago, so have been a little "away from the window", as we say in danish ;) Hope everything is well..

**Comment by brunsgaard** [comment]
Commit 23e614b570193023f784ed3565ead4aa2da6948b fixes this issue.

```
curl -k -X POST -d "client_id=KZCIGx...&grant_type=password&username=jonas&password=pass" https://localhost:5000/oauth/token
{"access_token": "FaPea...", "token_type": "Bearer", "refresh_token": "CnPz7..."}

curl -k -H "Authorization: Bearer FaPea..." https://localhost:5000/yolo
YOLO! Congraulations, you made it through and accessed the protected resource!

curl -k -d "client_id=KZCIGx...&token=FaPea..." https://localhost:5000/oauth/revoke

curl -k -H "Authorization: Bearer FaPea..." https://localhost:5000/yolo
401 Unauthorized
```

**Comment by EmergentBehavior** [comment]
I'll have to port this to the other branch eventually too. Also have to fix the broken SRefField as they will link to wrong field `_id`.

**Comment by EmergentBehavior** [comment]
In my own code I swapped out all the ObjectId-formatted user_id etc fields and just used string instead using gen_salt() like in `master`. Also for Token class, attributes should be updated like below (so proper records are obtained by proper ref field):

```
...
   client_id = db.StringField(required=True)
    user_id = db.StringField(required=True)
    token_type = db.StringField(max_length=40)
    access_token = db.StringField(max_length=40)
    refresh_token = db.StringField(max_length=40)
    expires = db.DateTimeField()
    scopes = ['']

    @property
    def user(self):
        """
        Return the user with the associated user_id.
        """
        return User.query.filter_by(id=self.user_id).first()

    @property
    def client(self):
        """
        Return the client with the associated client_id.
        """
        return Client.query.filter_by(client_id=self.client_id).first()
```

**Comment by EmergentBehavior** [comment]
Ok made the required changes in that branch.

**Comment by brunsgaard** [comment]
@EmergentBehavior nice ;) Edit: I will take a look at your commit and align the master branch soon, with the changes made to the model
